# Generated by Django 5.1.15 on 2025-12-18 19:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_errorlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__value': 'country'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_jobs', to='App.dropdownmaster'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__value': 'experience'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_jobs', to='App.dropdownmaster'),
        ),
        migrations.AddField(
            model_name='job',
            name='gender_preference',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__value': 'gender'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gender_jobs', to='App.dropdownmaster'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__value': 'job_category'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_jobs', to='App.dropdownmaster'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_fee_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__value': 'job_fee_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feetype_jobs', to='App.dropdownmaster'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__value': 'job_level'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_jobs', to='App.dropdownmaster'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__value': 'job_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_jobs', to='App.dropdownmaster'),
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification_required',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__value': 'qualification'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_jobs', to='App.dropdownmaster'),
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated skills', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='state_city',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__value': 'state_city'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_jobs', to='App.dropdownmaster'),
        ),
        migrations.AddField(
            model_name='job',
            name='temporary_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='total_openings',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__value': 'total_openings'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openings_jobs', to='App.dropdownmaster'),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Job Title'),
        ),
    ]
