# Generated by Django 5.2.9 on 2025-12-21 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_dashboardwidget_navigationgroup_quickaction_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.group')),
                ('role_identifier', models.CharField(choices=[('candidate', 'Candidate'), ('hiring_manager', 'Hiring Manager'), ('rpo_admin', 'RPO Admin')], help_text='Role identifier that matches Profile.role field', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group Profile',
                'verbose_name_plural': 'Group Profiles',
                'db_table': 'auth_group_profiles',
            },
        ),
    ]
