# Generated by Django 6.0 on 2025-12-21 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_resumeprocessing_error_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeJobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_match_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall compatibility percentage (0-100)', max_digits=5)),
                ('skills_match_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Skills compatibility percentage', max_digits=5)),
                ('experience_match_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Experience level compatibility', max_digits=5)),
                ('qualification_match_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Educational qualification match', max_digits=5)),
                ('location_match_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Location compatibility', max_digits=5)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Resume sentiment polarity score (-1 to 1)', null=True)),
                ('sentiment_impact', models.CharField(blank=True, help_text='Positive/Negative/Neutral impact on match', max_length=50)),
                ('matching_skills', models.JSONField(blank=True, help_text='List of skills that match job requirements', null=True)),
                ('missing_skills', models.JSONField(blank=True, help_text='List of required skills not found in resume', null=True)),
                ('additional_skills', models.JSONField(blank=True, help_text='Extra skills in resume not required by job', null=True)),
                ('success_reasons', models.JSONField(blank=True, help_text='List of reasons why candidate is a good match', null=True)),
                ('failure_reasons', models.JSONField(blank=True, help_text="List of reasons why candidate doesn't match", null=True)),
                ('improvement_suggestions', models.JSONField(blank=True, help_text='Suggestions for improving match score', null=True)),
                ('match_quality', models.CharField(blank=True, choices=[('excellent', 'Excellent Match (80-100%)'), ('good', 'Good Match (60-79%)'), ('fair', 'Fair Match (40-59%)'), ('poor', 'Poor Match (0-39%)')], help_text='Categorized match quality', max_length=20)),
                ('is_recommended', models.BooleanField(default=False, help_text='Whether candidate is recommended for this job')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('detailed_analysis', models.JSONField(blank=True, help_text='Complete analysis breakdown including all factors', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(help_text='Job posting being matched', on_delete=django.db.models.deletion.CASCADE, related_name='resume_matches', to='App.job')),
                ('matched_by', models.ForeignKey(blank=True, help_text='User who initiated the matching process', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_matches', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(help_text='Processed resume being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='App.resumeprocessing')),
            ],
            options={
                'verbose_name': 'Resume Job Match',
                'verbose_name_plural': 'Resume Job Matches',
                'db_table': 'resume_job_match',
                'ordering': ['-overall_match_percentage', '-created_at'],
                'indexes': [models.Index(fields=['job', 'overall_match_percentage'], name='resume_job__job_id_5d3f65_idx'), models.Index(fields=['resume', 'overall_match_percentage'], name='resume_job__resume__3254dd_idx'), models.Index(fields=['match_quality', 'is_recommended'], name='resume_job__match_q_42ce4b_idx'), models.Index(fields=['status', 'created_at'], name='resume_job__status_6d9e77_idx')],
                'unique_together': {('job', 'resume')},
            },
        ),
    ]
