# Generated by Django 5.2.9 on 2025-12-22 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_resumejobmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBoardMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('indeed', 'Indeed'), ('ziprecruiter', 'ZipRecruiter'), ('linkedin', 'LinkedIn'), ('jobelephant', 'JobElephant')], help_text='External job board name', max_length=20)),
                ('external_job_id', models.CharField(help_text='Job ID on the external board', max_length=255)),
                ('external_url', models.URLField(blank=True, help_text='Direct URL to job on external board', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('error', 'Error')], default='pending', max_length=20)),
                ('published_at', models.DateTimeField(auto_now_add=True, help_text='When the job was published to this board')),
                ('last_synced', models.DateTimeField(auto_now=True, help_text='Last time the job was synced to this board')),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the job was closed on this board', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if publication failed', null=True)),
                ('error_count', models.IntegerField(default=0, help_text='Number of errors encountered')),
                ('last_error_at', models.DateTimeField(blank=True, help_text='When the last error occurred', null=True)),
                ('view_count', models.IntegerField(default=0, help_text='Number of views on external board')),
                ('application_count', models.IntegerField(default=0, help_text='Number of applications from this board')),
                ('response_data', models.JSONField(blank=True, help_text='Full API response from board', null=True)),
                ('job', models.ForeignKey(help_text='Internal job posting', on_delete=django.db.models.deletion.CASCADE, related_name='board_mappings', to='App.job')),
            ],
            options={
                'verbose_name': 'Job Board Mapping',
                'verbose_name_plural': 'Job Board Mappings',
                'db_table': 'job_board_mapping',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_application_id', models.CharField(help_text='Application ID from external board', max_length=255, unique=True)),
                ('source', models.CharField(choices=[('indeed', 'Indeed'), ('ziprecruiter', 'ZipRecruiter'), ('linkedin', 'LinkedIn'), ('jobelephant', 'JobElephant'), ('direct', 'Direct Application')], default='direct', max_length=20)),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_phone', models.CharField(blank=True, max_length=30)),
                ('resume_url', models.URLField(blank=True, help_text='URL to resume on external board', null=True)),
                ('resume_file', models.FileField(blank=True, help_text='Downloaded resume file', null=True, upload_to='external_resumes/')),
                ('cover_letter', models.TextField(blank=True)),
                ('application_data', models.JSONField(blank=True, help_text='Full application data from board', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='new', max_length=20)),
                ('applied_at', models.DateTimeField(help_text='When candidate applied on external board')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When we received this application')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes about this application')),
                ('job', models.ForeignKey(help_text='Job being applied to', on_delete=django.db.models.deletion.CASCADE, related_name='external_applications', to='App.job')),
                ('board_mapping', models.ForeignKey(blank=True, help_text='Source board mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='App.jobboardmapping')),
            ],
            options={
                'verbose_name': 'External Application',
                'verbose_name_plural': 'External Applications',
                'db_table': 'external_application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('post', 'Post Job'), ('update', 'Update Job'), ('close', 'Close Job'), ('fetch_apps', 'Fetch Applications'), ('sync', 'Sync Status')], max_length=20)),
                ('board', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial Success')], max_length=20)),
                ('request_data', models.JSONField(blank=True, help_text='Data sent to external board', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Response from external board', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='App.job')),
                ('board_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='App.jobboardmapping')),
            ],
            options={
                'verbose_name': 'Board Sync Log',
                'verbose_name_plural': 'Board Sync Logs',
                'db_table': 'board_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobboardmapping',
            index=models.Index(fields=['board', 'status'], name='job_board_m_board_1909ee_idx'),
        ),
        migrations.AddIndex(
            model_name='jobboardmapping',
            index=models.Index(fields=['job', 'status'], name='job_board_m_job_id_cb001b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobboardmapping',
            index=models.Index(fields=['external_job_id'], name='job_board_m_externa_f44e0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobboardmapping',
            unique_together={('job', 'board')},
        ),
        migrations.AddIndex(
            model_name='externalapplication',
            index=models.Index(fields=['job', 'status'], name='external_ap_job_id_a331e7_idx'),
        ),
        migrations.AddIndex(
            model_name='externalapplication',
            index=models.Index(fields=['source', 'status'], name='external_ap_source_33de97_idx'),
        ),
        migrations.AddIndex(
            model_name='externalapplication',
            index=models.Index(fields=['candidate_email'], name='external_ap_candida_bd5ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='boardsynclog',
            index=models.Index(fields=['board', 'status'], name='board_sync__board_99de0b_idx'),
        ),
        migrations.AddIndex(
            model_name='boardsynclog',
            index=models.Index(fields=['action', 'status'], name='board_sync__action_0f6ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='boardsynclog',
            index=models.Index(fields=['-started_at'], name='board_sync__started_656763_idx'),
        ),
    ]
