# Generated by Django 6.0 on 2025-12-25 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_jobboardmapping_externalapplication_boardsynclog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeprocessing',
            name='candidate_name',
            field=models.CharField(blank=True, help_text='Extracted candidate name from resume', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumeprocessing',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Job associated with this resume upload', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_processings', to='App.job'),
        ),
        migrations.AddField(
            model_name='resumeprocessing',
            name='resumesource',
            field=models.ForeignKey(blank=True, help_text='Resume source company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_processings', to='App.dropdownmaster'),
        ),
    ]
