# Generated by Django 6.0 on 2025-12-25 10:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_resumeprocessing_candidate_name_resumeprocessing_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeprocessing',
            name='job',
            field=models.ForeignKey(
                to='App.Job',
                on_delete=models.CASCADE,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name='resumeprocessing',
            name='resumesource',
            field=models.ForeignKey(
                to='App.DropdownMaster',
                on_delete=models.SET_NULL,
                null=True,
                blank=True,
            ),
        ),
    ]
