# Generated by Django 5.2.9 on 2025-12-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20251225_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeprocessing',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Job associated with this resume upload', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_processings', to='App.job'),
        ),
        migrations.AlterField(
            model_name='resumeprocessing',
            name='resumesource',
            field=models.ForeignKey(blank=True, help_text='Resume source company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_processings', to='App.dropdownmaster'),
        ),
    ]
