# Generated by Django 6.0 on 2025-12-24 01:36

import django.db.models.deletion
import video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=video.models.video_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_recording', to='calls.callsession')),
            ],
        ),
    ]
